Remove third-party dependencies from GitHub Actions workflow
lwojcik/eleventy-template-bliss pull request #115
Opened 2024-04-05 23:34 UTC by lucascantor

Use modern GitHub Actions deployment method for GitHub Pages

2024-04-05 23:49 UTC, lwojcik commented
Hi @lucascantor, this looks like a great PR. Thanks a lot!

I'll give it some testing around the weekend and merge it soon.

2024-04-05 23:53 UTC, lucascantor commented
Honestly I'm not super confident I have the expertise to say this is better, but IMHO rlominating unofficial / third-party GitHub Actions is ideal where possible.

I also think this means you can remove the `build-gh-pages` script in `package.json` entirely...?

2024-04-08 18:15 UTC, lwojcik commented
>Honestly I'm not super confident I have the expertise to say this is better, but in my humble opinion, eliminating unofficial / third-party GitHub Actions is ideal where possible.

I agree. What you provided is way better and cleaner.

>I also think this means you can remove the build-gh-pages script in package.json entirely...?

I'm not sure. The point of `npm run build-gh-pages` is to provide a working example of a GitHub Pages deployment (e.g. [inside a custom subdirectory](https://lwojcik.github.io/eleventy-template-bliss/) provided by `pathPrefix` property) _alongside_ [the same setup intended for domain root](https://eleventy-bliss.lkmt.us/). Even after the changes provided by you, the Action still uses `npm run build-gh-pages` to build the site.

2024-04-08 18:16 UTC, lwojcik requested changes

2024-04-08 18:16 UTC, lwojcik commented on README.md
> -2. In `package.json`, find the following line:
In relation to [this comment](https://github.com/lwojcik/eleventy-template-bliss/pull/115#issuecomment-2043388917), this point has to stay in the manual for now. Please revert it.

2024-04-08 19:10 UTC, lwojcik approved these changes

2024-04-08 19:11 UTC, lwojcik commented
@lucascantor awesome job, thank you very much!

Merging it now, will also update [my blog post](https://blog.lukaszwojcik.net/eleventy-pathprefix-and-github-pages/) and credit you.

2024-04-08 19:11 UTC, merged